version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_libreria_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: libreria_user
      POSTGRES_PASSWORD: libreria_password
      POSTGRES_DB: libreria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
