name: FastAPI CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-app:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///./test.db"
      SECRET_KEY: "secret-key-for-testing"
      UPLOAD_DIR: "uploads"
      MAX_ALLOWED_LOANS: 3
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

      #Mocks de servidor de correo
      MAIL_USERNAME: "usuario_falso"
      MAIL_PASSWORD: "password_falso"
      MAIL_FROM: "test@test.com"
      MAIL_PORT: 587
      MAIL_SERVER: "localhost"
      MAIL_FROM_NAME: "Test System"
      SUPPRESS_SEND: 1 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create uploads uploads directory
        run: mkdir -p uploads

      - name: Run tests
        run: |
          python -m pytest -v
